init tenders schema

Revision ID: 8b0280093b61
Revises: 
Create Date: 2026-07-09 06:34:14.370102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b0280093b61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('ogrn', sa.String(length=15), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('full_name', sa.String(length=2048), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_inn'), 'customers', ['inn'], unique=False)
    op.create_index(op.f('ix_customers_region'), 'customers', ['region'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('EIS_44FZ', 'EIS_223FZ', 'EIS_615PP', 'B2B_CENTER', 'FABRIKANT', 'RTS_TENDER', 'SBERBANK_AST', 'BANKRUPTCY_EFRSB', 'OTHER', name='tender_source'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('law', sa.Enum('FZ_44', 'FZ_223', 'PP_615', 'COMMERCIAL', 'BANKRUPTCY', name='procurement_law'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('okpd2_codes', sa.ARRAY(sa.String(length=20)), server_default='{}', nullable=False),
    sa.Column('okved_codes', sa.ARRAY(sa.String(length=20)), server_default='{}', nullable=False),
    sa.Column('procurement_method', sa.Enum('ELECTRONIC_AUCTION', 'OPEN_TENDER', 'OPEN_TENDER_LIMITED', 'TWO_STAGE_TENDER', 'REQUEST_FOR_QUOTATIONS', 'REQUEST_FOR_PROPOSALS', 'SINGLE_SUPPLIER', 'COMMERCIAL_OTHER', 'UNKNOWN', name='procurement_method'), nullable=False),
    sa.Column('status', sa.Enum('PUBLISHED', 'CLARIFICATION', 'SUBMISSION_OPEN', 'SUBMISSION_CLOSED', 'SUMMARIZING', 'COMPLETED', 'CANCELLED', 'UNKNOWN', name='tender_status'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('initial_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('delivery_place', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summarizing_date', sa.Date(), nullable=True),
    sa.Column('requires_smp_sonko', sa.Boolean(), nullable=False),
    sa.Column('security_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_tender_source_external_id')
    )
    op.create_index('ix_tender_law_status', 'tenders', ['law', 'status'], unique=False)
    op.create_index('ix_tender_okpd2', 'tenders', ['okpd2_codes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_tenders_external_id'), 'tenders', ['external_id'], unique=False)
    op.create_index(op.f('ix_tenders_law'), 'tenders', ['law'], unique=False)
    op.create_index(op.f('ix_tenders_procurement_method'), 'tenders', ['procurement_method'], unique=False)
    op.create_index(op.f('ix_tenders_published_at'), 'tenders', ['published_at'], unique=False)
    op.create_index(op.f('ix_tenders_region'), 'tenders', ['region'], unique=False)
    op.create_index(op.f('ix_tenders_source'), 'tenders', ['source'], unique=False)
    op.create_index(op.f('ix_tenders_status'), 'tenders', ['status'], unique=False)
    op.create_index(op.f('ix_tenders_submission_deadline'), 'tenders', ['submission_deadline'], unique=False)
    op.create_table('tender_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('storage_path', sa.String(length=2048), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tender_documents')
    op.drop_index(op.f('ix_tenders_submission_deadline'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_source'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_region'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_published_at'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_procurement_method'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_law'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_external_id'), table_name='tenders')
    op.drop_index('ix_tender_okpd2', table_name='tenders', postgresql_using='gin')
    op.drop_index('ix_tender_law_status', table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_customers_region'), table_name='customers')
    op.drop_index(op.f('ix_customers_inn'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
